@baseURL = https://localhost:5001/api/v1

# @name login
POST {{baseURL}}/session HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "name": "admin",
  "password": "letmein1"
}

###
@authToken = {{login.response.body.output.token}}

GET {{baseURL}}/robots/tahi/logs HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{authToken}}

###

GET {{baseURL}}/robots/tahi/logs/7 HTTP/1.1
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{authToken}}

###

POST {{baseURL}}/robots/tahi/logs HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "action": "init",
  "version": "1.2.3"
}

###

POST {{baseURL}}/robots/tahi/logs HTTP/1.1
Content-Type: application/json; charset=utf-8

{
  "action": "log",
  "time": 5,
  "messages": [
    "1:action:Backward",
    "7:action:Left Curve",
    "18:action:Forward"
  ]
}

###

GET {{baseURL}}/robots/toru/logs/46/playback HTTP/1.1
Content-Type: text/plain; charset=utf-8

###
